### ISSUE TITLE
Using px-datetime-range-panel standalone

### ISSUE THREAD

**Issue by ghost** [PredixDev/px-datetime-range-panel#5]
Can this component be used standalone without px-rangepicker? If so, the apply button is not properly listening to the event.

**Comment by benoitjchevalier** [comment]
This component wasn't meant to be used standalone but I think I've seen people using it. What do you mean by the apply button not listening to the event? Did you mean fire?

**Comment by ghost** [comment]
In the console I can see that the 'px-datetime-button-clicked' event is fired. However it seems that the px-datetime-field, which is supposed to be listening for this event, isn't doing so. I wasn't sure if that capability will only work in the px-rangepicker component.

**Comment by benoitjchevalier** [comment]
I'm still confused as to what the issue is. px-datetime-field doesn't exist in the px-datetime-range-panel.

However we noticed that our demo is out of sync regarding the event name, it shouldn't watch for `px-datetime-submited` or `px-datetime-range-submited` but for `px-calendar-range-submitted`. That could be the source of the confusion.

@Menkhaus-ge will fix the demo soon

**Comment by katemenkhaus** [comment]
The correct EvenListeners have been updated. 
If you would like to use the button clicked event, I would suggest looking at px-rangepicker to see how we are handling this event.

**Comment by randyaskin** [comment]
Sounds like this issue can be closed? Please comment here if your issue is not resolved.
